kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
bindAddress: 0.0.0.0
metricsBindAddress: 0.0.0.0:10249
clientConnection:
  kubeconfig: /home/ubuntu/kube-proxy/kube-proxy.kubeconfig
hostnameOverride: k8s-master1
clusterCIDR: 10.255.0.0/16