version: "3"

services:
  etcd1:
    image: quay.io/coreos/etcd:v3.4.14
    container_name: etcd1
    restart: always
    ports:
      - 12379:2379
      - 12380:2380
    environment:
      ETCDCTL_API: 3
    volumes:
      - $HOME/docker/etcd/etcd-data:/etcd-data
    command: etcd -name etcd1 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    networks:
      - etcd

  etcd2:
    image: quay.io/coreos/etcd:v3.4.14
    container_name: etcd2
    restart: always
    ports:
      - 22379:2379
      - 22380:2380
    environment:
      ETCDCTL_API: 3
    volumes:
      - $HOME/docker/etcd/etcd-data:/etcd-data
    command: etcd -name etcd2 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    networks:
      - etcd

  etcd3:
    image: quay.io/coreos/etcd:v3.4.14
    container_name: etcd3
    restart: always
    ports:
      - 32379:2379
      - 32380:2380
    environment:
      ETCDCTL_API: 3
    volumes:
      - $HOME/docker/etcd/etcd-data:/etcd-data
    command: etcd -name etcd3 -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379 -listen-peer-urls http://0.0.0.0:2380 -initial-cluster-token etcd-cluster -initial-cluster "etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd3:2380" -initial-cluster-state new
    networks:
      - etcd

networks:
  etcd:
    # external: true